version: '3'
services:
  server:
    image: registry.gitlab.com/commento/commento
    ports:
      - 8081:8080
    environment:
      COMMENTO_ORIGIN: '${COMMENTO_ORIGIN}'
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db
    networks:
      - db_network
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

networks:
  db_network:

volumes:
  postgres_data_volume:
