version: "3"

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    expose:
      - "3306"
    volumes:
      - acrarium_data:/var/lib/mysql
  acrarium:
    image: f43nd1r/acrarium:latest
    container_name: acrarium
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/acrarium?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: '${MYSQL_USER}'
      SPRING_DATASOURCE_PASSWORD: '${MYSQL_PASSWORD}'
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL57Dialect

volumes:
  acrarium_data:
